library: /music/meta/beets.db
directory: /music
original_date: yes
per_disc_numbering: yes
paths:
  default: $albumartist/$album%aunique{}/%if{$multidisc,${disc}_}${track}_${title}
  comp: Various_Artists/$album/%if{$multidisc,${disc}_}${track}_${title}_\(${artist}\)
  singleton: $artist/$title
asciify_paths: yes
clutter: .AppleDouble .DS_Store Thumbs.DB
art_filename: cover
ui:
  color: yes
import:
  resume: ask
  incremental_skip_later: yes
  log: /music/meta/beets-import.log
replace:
  '\s+': _
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '^\s+': ''
  '^-': _
plugins: inline missing chroma mbsync scrub zero fetchart smartplaylist info missing
item_fields:
  multidisc: 1 if disctotal > 1 else 0
chroma:
  auto: yes
acoustid:
  apikey: W1GHyruT
scrub:
  auto: yes
musicbrainz:
  genres: yes
smartplaylist:
  relative_to: /music
  playlist_dir: /music/playlists
  playlists:
    - name: '{$original_year[:2]}0s.m3u'
      query: ['original_year::(1|2)\d{3}']
    - name: '%left{$year,3}0s.m3u'
      query: 'year::^(1|2)'
    - name: 'TODOFormat.m3u'
      query: ['format:MP3']
    - name: 'TODOGain.m3u'
      query: ['rg_track_gain::^$ format:FLAC']
    - name: 'TODOMeta.m3u'
      query: ['mb_albumid::^$', 'original_year::^[^12]']
zero:
  fields: images
  comments: [EAC, LAME, from.+collection, 'ripped by']
  update_database: true
